
  image: docker
  services:
    - docker:dind
  
  stages:
    - build
    - deploy
  .build-env:
    stage: build
    script:
      - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
      - docker build -t $CI_REGISTRY_IMAGE .
      - docker push $CI_REGISTRY_IMAGE
  
  deploy:
    stage: deploy
    script:
      - eval $(ssh-agent -s)
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
      - chmod 600 ~/.ssh/known_hosts
      - >
        ssh $SSH_USER@$SSH_SERVER_IP
        "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
        cd ${PATH_TO_PROJECT};
        docker-compose down;
        docker pull ${CI_REGISTRY_IMAGE}:latest;
        docker-compose up -d;
        docker image prune -f;"